import SwiftUI

let exercises: [Exercises] = [
    Exercises(bodyPart: NSLocalizedString("Head", comment: "Body part name"), exercise: NSLocalizedString("TenseNeckDesc", comment: "Neck Exercise Description"), titleExercise: NSLocalizedString("NeckEx", comment: "Title for neck exercise")),
    Exercises(bodyPart: NSLocalizedString("Head", comment: "Body part name"), exercise: NSLocalizedString("ChinChest", comment: "Tense Neck Exercise Description"), titleExercise: NSLocalizedString("TenseNeck", comment: "Tense Neck Exercise")),
    Exercises(bodyPart: NSLocalizedString("Head", comment: "Body part name"), exercise: NSLocalizedString("GoodPosture", comment: "Posture exercise description"), titleExercise: NSLocalizedString("Posture", comment: "Posture title")),
    Exercises(bodyPart: NSLocalizedString("Eye", comment: "Body part name"), exercise: NSLocalizedString("FocusBlink", comment: "Eye exercise description"), titleExercise: NSLocalizedString("EyeEx", comment: "Eye Exercise title")),
    Exercises(bodyPart: NSLocalizedString("Eye", comment: "Body part name"), exercise: NSLocalizedString("BrowBreathe", comment: "Eyebrow contraction exercise description"), titleExercise: NSLocalizedString("BrowCont", comment: "Eyebrow contraction title")),
    Exercises(bodyPart: NSLocalizedString("Nose", comment: "Body part name"), exercise: NSLocalizedString("InhaleExhale", comment: "Nasal breathing exercise description"), titleExercise: NSLocalizedString("NasalBreath", comment: "Nasal breathing title")),
    Exercises(bodyPart: NSLocalizedString("Nose", comment: "Body part name"), exercise: NSLocalizedString("PullNose", comment: "Nose tension exercise description"), titleExercise: NSLocalizedString("NoseTense", comment: "Nose tension title")),
    Exercises(bodyPart: NSLocalizedString("Hand", comment: "Body part name"), exercise: NSLocalizedString("HandsLegs", comment: "Hand exercise description"), titleExercise: NSLocalizedString("HandEx", comment: "Hand Exercise title")),
    Exercises(bodyPart: NSLocalizedString("Hand", comment: "Body part name"), exercise: NSLocalizedString("FistsPress", comment: "Tight fists exercise description"), titleExercise: NSLocalizedString("TightFists", comment: "Tight Fists title")),
    Exercises(bodyPart: NSLocalizedString("Hand", comment: "Body part name"), exercise: NSLocalizedString("PushObject", comment: "Hand push exercise description"), titleExercise: NSLocalizedString("HandPush", comment: "Hand Push title")),
    Exercises(bodyPart: NSLocalizedString("Hand", comment: "Body part name"), exercise: NSLocalizedString("HandsStomach", comment: "Hand clasp exercise description"), titleExercise: NSLocalizedString("HandClasp", comment: "Hand Clasp title")),
    Exercises(bodyPart: NSLocalizedString("Leg", comment: "Body part name"), exercise: NSLocalizedString("HeelsFloor", comment: "Leg exercise description"), titleExercise: NSLocalizedString("LegEx", comment: "Leg Exercise title")),
    Exercises(bodyPart: NSLocalizedString("Leg", comment: "Body part name"), exercise: NSLocalizedString("KneesTogether", comment: "Tight knees exercise description"), titleExercise: NSLocalizedString("TightKnees", comment: "Tight Knees title")),
    Exercises(bodyPart: NSLocalizedString("Leg", comment: "Body part name"), exercise: NSLocalizedString("StandHeels", comment: "Heels exercise description"), titleExercise: NSLocalizedString("HeelsWeight", comment: "Weight on Heels title")),
    Exercises(bodyPart: NSLocalizedString("Mouth", comment: "Body part name"), exercise: NSLocalizedString("LipsTeeth", comment: "Mouth exercise description"), titleExercise: NSLocalizedString("MouthEx", comment: "Mouth Exercise title")),
    Exercises(bodyPart: NSLocalizedString("Mouth", comment: "Body part name"), exercise: NSLocalizedString("JawLips", comment: "Jaw clenching exercise description"), titleExercise: NSLocalizedString("JawClench", comment: "Jaw Clenching title")),
    Exercises(bodyPart: NSLocalizedString("Mouth", comment: "Body part name"), exercise: NSLocalizedString("CloseTeeth", comment: "Lip closure exercise description"), titleExercise: NSLocalizedString("LipClose", comment: "Lip Closure title")),
    Exercises(bodyPart: NSLocalizedString("Arm", comment: "Body part name"), exercise: NSLocalizedString("FingersArms", comment: "Interlaced arms exercise description"), titleExercise: NSLocalizedString("InterlacedArms", comment: "Interlaced Arms title")),
    Exercises(bodyPart: NSLocalizedString("Shoulder", comment: "Body part name"), exercise: NSLocalizedString("ElbowsHips", comment: "Thigh push exercise description"), titleExercise: NSLocalizedString("ThighPush", comment: "Thigh Push title")),
    Exercises(bodyPart: NSLocalizedString("Shoulder", comment: "Body part name"), exercise: NSLocalizedString("ShouldersDown", comment: "Lowered shoulders exercise description"), titleExercise: NSLocalizedString("LowShoulders", comment: "Lowered Shoulders title")),
    Exercises(bodyPart: NSLocalizedString("Foot", comment: "Body part name"), exercise: NSLocalizedString("BendKnees", comment: "Crossed feet position exercise description"), titleExercise: NSLocalizedString("CrossFeet", comment: "Crossed Feet Position title")),
    Exercises(bodyPart: NSLocalizedString("Foot", comment: "Body part name"), exercise: NSLocalizedString("SoleToes", comment: "Toe lift exercise description"), titleExercise: NSLocalizedString("ToeLift", comment: "Toe Lift title"))
]
